--AWOOLIM ALL TABLE
--회원
CREATE TABLE MEMBER(
    USERID NUMBER NOT NULL, 				        --SEQUENCE
    USEREMAIL VARCHAR2(100) NOT NULL,		        --이메일
    PASSWORD VARCHAR2(100) NULL, 			        --비밀번호
    USERNAME VARCHAR2(20) NOT NULL,		            --이름
    USERBIRTH VARCHAR2(30) NOT NULL,		        --생년월일
    USERPHONE VARCHAR2(30) NOT NULL,    	        --전화번호
    USERGENDER VARCHAR2(10) NOT NULL,		        --성별
    NICKNAME VARCHAR2(30) NULL,			            --닉네임
    USERIMAGE VARCHAR2(100) NULL,			        --프로필 사진
    USERBACKIMAGE VARCHAR2(100) NULL,		        --프로필 배경사진
    USERINTRO VARCHAR2(200) NULL,		            --한줄 소개
    WARNINGCOUNT NUMBER DEFAULT 0 NOT NULL,         --경고
    SNSTYPE VARCHAR2(20) DEFAULT 'default' NOT NULL,--회원가입 방법(google,kakao,naver,defaulf)
    ROLE VARCHAR2(20)DEFAULT 'ROLE_MEMBER' NOT NULL --권한
);

ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_PK PRIMARY KEY (USERID);
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_UNIQUE UNIQUE (USERPHONE);

CREATE SEQUENCE MEMBER_SEQ
START WITH 1
INCREMENT BY 1;

-----------------------------------------------------------------------------
--관리자 
CREATE TABLE ADMIN(
    USERID NUMBER NOT NULL,
    USEREMAIL VARCHAR2(20) NOT NULL, 	                --관리자 아이디
    PASSWORD VARCHAR2(100) NOT NULL,	                --관리자 비밀번호
    ROLE VARCHAR2(20) DEFAULT 'ROLE_ADMIN' NOT NULL 	--권한
);
ALTER TABLE ADMIN ADD CONSTRAINT ADMIN_PK PRIMARY KEY(USERID);
-----------------------------------------------------------------------------
--모임
CREATE TABLE CLUB(
    CLUBNO NUMBER NOT NULL,					            --seq사용 번호
    CLUBTITLE VARCHAR2(300) NOT NULL,				    --모임이름
    CLUBGENDER VARCHAR2(30) DEFAULT '제한없음' NOT NULL,	--모집 성별
	AGELIMIT VARCHAR(40) DEFAULT '제한없음' NOT NULL,     --모집 나이
    CATEGORY VARCHAR2(40) NOT NULL,				        --카테고리
 	CITY VARCHAR2(50) NOT NULL,				            --도시
    DISTRICT VARCHAR2(20) DEFAULT '전체' NOT NULL,		--시군구
	REGULARTYPE NUMBER(1) NOT NULL,			            --정기모임 1 일회성 0
	MAXMEMBER NUMBER DEFAULT 100 NOT NULL,              --0은 제한없음
	USERID NUMBER NOT NULL,                             --모임장
	DDAY VARCHAR2(100) NOT NULL,					    --지정 날짜
	CLUBIMAGE VARCHAR2(100) NULL,		                --모임 프로필 이미지
	DETAILINFO VARCHAR2(4000) NULL, 			        --상세정보
	RECRUITMENT NUMBER(1) DEFAULT 1 NOT NULL, 	        --모집중 1 모집마감 0
    MEMBERCOUNT NUMBER DEFAULT 0 NOT NULL               --모임 인원
);			
ALTER TABLE CLUB ADD CONSTRAINT CLUB_PK PRIMARY KEY (CLUBNO);

ALTER TABLE CLUB ADD CONSTRAINT CLUB_MEMBER_FK FOREIGN KEY (USERID)
REFERENCES MEMBER (USERID) ON DELETE CASCADE;

CREATE SEQUENCE CLUB_SEQ
    START WITH 1
    INCREMENT BY 1;

-----------------------------------------------------------------------------
--모임 멤버
CREATE TABLE CLUBMEMBER(
	MEMBERNO NUMBER NOT NULL, 		        --모임멤버 번호
	CLUBNO NUMBER NOT NULL,			        --모임 번호
	USERID NUMBER NOT NULL,		            --유저 아이디
	REGDATE DATE DEFAULT SYSDATE NOT NULL,  --가입일,신청일
	ISACCEPT NUMBER(1) DEFAULT 0 NOT NULL	--수락여부 FALSE 0 true 1
);

ALTER TABLE CLUBMEMBER ADD CONSTRAINT CLUBMEMBER PRIMARY KEY (MEMBERNO);

ALTER TABLE CLUBMEMBER ADD CONSTRAINT MEMBER_CLUBMEMBER_FK FOREIGN KEY 
(USERID) REFERENCES MEMBER (USERID) ON DELETE CASCADE;

ALTER TABLE CLUBMEMBER ADD CONSTRAINT CLUB_CLUBMEMBER_FK FOREIGN KEY
(CLUBNO) REFERENCES CLUB (CLUBNO) ON DELETE CASCADE;

CREATE SEQUENCE CLUBMEMBER_SEQ
    START WITH 1
    INCREMENT BY 1;

-----------------------------------------------------------------------------
--모임 사진첩
CREATE TABLE CLUBGALLERY(
	PICNO NUMBER NOT NULL,			            --사진 번호
	USERID NUMBER NULL,				            --유저 아이디
	CLUBNO NUMBER NOT NULL,			            --모임번호
	REGDATE DATE DEFAULT SYSDATE NOT NULL,  	--사진 업로드일
	IMAGE VARCHAR(100) NOT NULL		            --사진
);

ALTER TABLE CLUBGALLERY ADD CONSTRAINT CLUBGALLERY PRIMARY KEY(PICNO);

ALTER TABLE CLUBGALLERY ADD CONSTRAINT MEMBER_CLUBGALLERY_FK FOREIGN KEY
(USERID) REFERENCES MEMBER (USERID) ON DELETE SET NULL;

ALTER TABLE CLUBGALLERY ADD CONSTRAINT CLUB_CLUBGALLERY_FK FOREIGN KEY
(CLUBNO) REFERENCES CLUB (CLUBNO) ON DELETE CASCADE;

CREATE SEQUENCE CLUBGALLERY_SEQ
    START WITH 1
    INCREMENT BY 1;

-----------------------------------------------------------------------------
--모임 일정   모임 생성시 정기/일회성 만남 일자 생성 TRIGGER
CREATE TABLE CLUBSCHEDULE(
	SCHEDULENO NUMBER NOT NULL,			--일정 번호
	CLUBNO NUMBER NOT NULL,				--모임번호
	DDAY VARCHAR2(100) NOT NULL,		--모임일 
	CONTENT VARCHAR2(400) NOT NULL		--모임 내용
);
ALTER TABLE CLUBSCHEDULE ADD CONSTRAINT SCHEDULE_PK PRIMARY KEY(SCHEDULENO);

ALTER TABLE CLUBSCHEDULE ADD CONSTRAINT CLUN_SCHDULE_FK FOREIGN KEY
(CLUBNO) REFERENCES CLUB (CLUBNO) ON DELETE CASCADE;

CREATE SEQUENCE CLUBSCHEDULE_SEQ
    START WITH 1
    INCREMENT BY 1;

-----------------------------------------------------------------------------
--신고 
CREATE TABLE REPORT(
    REPORTNO NUMBER NOT NULL,		        --신고 번호
    USERID NUMBER NOT NULL,		            --신고자 아이디
    TARGETID NUMBER NOT NULL,		        --신고 대상
    TYPE VARCHAR2(30) NOT NULL,             --신고 대상 타입(모임,유저)
    CONTENT VARCHAR2(200) NOT NULL,		    --신고 내용
    REGDATE DATE DEFAULT SYSDATE NOT NULL,	--신고일
    RESULT NUMBER(1) DEFAULT 0 NOT NULL,  	--경고 1 처리전 0  넘어감 -1 
    RESULTMESSAGE VARCHAR2(500) NULL	    --관리자 신고처리 메시지
);
ALTER TABLE REPORT ADD CONSTRAINT REPORT_PK PRIMARY KEY (REPORTNO);

ALTER TABLE REPORT ADD CONSTRAINT MEMBER_REPORT_PK FOREIGN KEY
(USERID) REFERENCES MEMBER (USERID) ON DELETE CASCADE;

CREATE SEQUENCE REPORT_SEQ
    START WITH 1
    INCREMENT BY 1;

-----------------------------------------------------------------------------
--자주하는 질문
CREATE TABLE QUESTION(
	QUESTIONNO NUMBER NOT NULL,			    --질문 번호
	CATEGORY VARCHAR2(40) NOT NULL,			--질문 카테고리
	TITLE VARCHAR2(300) NOT NULL,			--질문 제목
	ANSWER VARCHAR2(1000) NOT NULL			--답변
);
ALTER TABLE QUESTION ADD CONSTRAINT QUESTION_PK PRIMARY KEY(QUESTIONNO);
 
CREATE SEQUENCE QUESTION_SEQ
    START WITH 1
    INCREMENT BY 1;
    
-----------------------------------------------------------------------------
--공지사항
CREATE TABLE NOTICE(
	NOTICENO NUMBER NOT NULL,			    --공지사항 번호 
	KEYWORD VARCHAR2(50) NOT NULL,			--공지사항 키워드
	TITLE VARCHAR2(500) NOT NULL,			--공지사항 제목
	CONTENT VARCHAR2(3000) NOT NULL,		--공지사항 내용
	COUNT NUMBER DEFAULT 0 NOT NULL,		--조회수
    REGDATE DATE DEFAULT SYSDATE NOT NULL 	--작성일
);
ALTER TABLE NOTICE ADD CONSTRAINT NOTICE_PK PRIMARY KEY(NOTICENO);

CREATE SEQUENCE NOTICE_SEQ
    START WITH 1
    INCREMENT BY 1;
    
-----------------------------------------------------------------------------
--TRIGGER CLUBMEMBER INSERT , CLUBMEMBER UPDATE,REPORT UPDATE
--알림 (신청했을경우,수락했을 경우, 신고 처리됨(신고자), 제제대상 경고메세지)
CREATE TABLE ALARM(
	ALARMNO NUMBER NOT NULL,    		    --알림 번호
	USERID NUMBER NOT NULL,			        --유저 아이디
	MESSAGE VARCHAR2(300) NOT NULL,			--알림 메시지
	ISREAD NUMBER(1) DEFAULT 0 NOT NULL     --읽음 1 안읽음 0
);

ALTER TABLE ALARM ADD CONSTRAINT ALARM_PK PRIMARY KEY (ALARMNO);

ALTER TABLE ALARM ADD CONSTRAINT MEMBER_ALARM_FK FOREIGN KEY
(USERID) REFERENCES MEMBER (USERID) ON DELETE CASCADE;

CREATE SEQUENCE ALARM_SEQ
    START WITH 1
    INCREMENT BY 1;
    
-----------------------------------------------------------------------------
--채팅방
CREATE TABLE CHATROOM(
    CHATROOMNO NUMBER NOT NULL,        --채팅방 번호
    CLUBNO NUMBER NOT NULL,
    CHATROOMNAME VARCHAR2(300) NOT NULL--모임 번호
);
ALTER TABLE CHATROOM ADD CONSTRAINT CHATROOM_PK PRIMARY KEY(CHATROOMNO);

ALTER TABLE CHATROOM ADD CONSTRAINT CLUB_CHATROOM_FK FOREIGN KEY
(CLUBNO) REFERENCES CLUB (CLUBNO) ON DELETE CASCADE;

CREATE SEQUENCE CHATROOM_SEQ
    START WITH 1
    INCREMENT BY 1;
-----------------------------------------------------------------------------
--채팅
CREATE TABLE CHAT(
	CHATNO NUMBER NOT NULL,			        --채팅번호
	CLUBNO NUMBER NOT NULL,			        --모임 번호
	USERID NUMBER NOT NULL,			        --채팅한 유저 아이디
	MESSAGE VARCHAR2(500) NOT NULL,		    --채팅 내용
	REGDATE DATE DEFAULT SYSDATE NOT NULL 	--채팅한 날짜
);
ALTER TABLE CHAT ADD CONSTRAINT CHAT_PK PRIMARY KEY (CHATNO);

ALTER TABLE CHAT ADD CONSTRAINT MEMBER_CHAT_FK FOREIGN KEY
(USERID) REFERENCES MEMBER (USERID) ON DELETE SET NULL;

ALTER TABLE CHAT ADD CONSTRAINT CLUB_CHAT_FK FOREIGN KEY
(CLUBNO) REFERENCES CLUB (CLUBNO) ON DELETE CASCADE;

CREATE SEQUENCE CHAT_SEQ
    START WITH 1
    INCREMENT BY 1;
    
-----------------------------------------------------------------------------
--JWT refreshToken 정보
CREATE TABLE REFRESHTOKEN(
    ID NUMBER NOT NULL,                 --토큰 번호
    USERID NUMBER NOT NULL,             --유저 아이디
    USEREMAIL VARCHAR2(100) NOT NULL,   --유저 이메일
    REFRESH VARCHAR2(300) NOT NULL,     --암호화 토큰 문자
    EXPIRATION VARCHAR2(100) NOT NULL   --생명주기
);
ALTER TABLE REFRESHTOKEN ADD CONSTRAINT REFRESHTOKEN_PK PRIMARY KEY(ID);

CREATE SEQUENCE REFRESHTOKEN_SEQ
    START WITH 1
    INCREMENT BY 1;