--초기화
--테이블
DROP TABLE REFRESHTOKEN;
DROP TABLE CHAT;
DROP TABLE CHATROOM;
DROP TABLE ALARM;
DROP TABLE NOTICE;
DROP TABLE QUESTION;
DROP TABLE REPORT;
DROP TABLE CLUBSCHEDULE;
DROP TABLE CLUBGALLERY;
DROP TABLE CLUBMEMBER;
DROP TABLE CLUB;
DROP TABLE ADMIN;
DROP TABLE MEMBER;

--시퀀스
DROP SEQUENCE REFRESHTOKEN_SEQ;
DROP SEQUENCE CHAT_SEQ;
DROP SEQUENCE CHATROOM_SEQ;
DROP SEQUENCE ALARM_SEQ;
DROP SEQUENCE NOTICE_SEQ;
DROP SEQUENCE QUESTION_SEQ;
DROP SEQUENCE REPORT_SEQ;
DROP SEQUENCE CLUBSCHEDULE_SEQ;
DROP SEQUENCE CLUBGALLERY_SEQ;
DROP SEQUENCE CLUBMEMBER_SEQ;
DROP SEQUENCE CLUB_SEQ;
DROP SEQUENCE MEMBER_SEQ;
